### ISSUE TITLE
Alignment needs to be done in mentor section 

### ISSUE THREAD

**Issue by kapilG0** [omrajsharma/bigohhh.com#104]
In mobile view alignment needs to be done in mentor section 
![Screenshot_20240516_122208](https://github.com/omrajsharma/bigohhh.com/assets/59639410/bb81abc6-da11-4999-a55d-70acaad78ee3)

**Comment by kapilG0** [comment]
Hello @omrajsharma please assign this issue to me under gssoc 24

**Comment by PriyankaRaskhit** [comment]
Hi, please assign this issue to me under GSSOC 24

**Comment by HareRamDwivedi** [comment]
Hello, please assign me this issue I have experience in React and made many projects, assign me this issue under the GSSOC'24

**Comment by omrajsharma** [comment]
I feel alignment is fine, where is the issue. Can you please highlight?

**Comment by kapilG0** [comment]
> I feel alignment is fine, where is the issue. Can you please highlight?

@omrajsharma As you can see forward arrow and backward arrow overlap the other div that is the issue I am thinking please correct me if I am wrong

**Comment by omrajsharma** [comment]
@kapilG0 left and right can be aligned. I'm assigning this issue to you. If you need any help then do let me know.

**Comment by kapilG0** [comment]
> @kapilG0 left and right can be aligned. I'm assigning this issue to you. If you need any help then do let me know.

sure please assign this issue to me under gssoc 24 @omrajsharma

**Comment by omrajsharma** [comment]
I'm assigning this issue to you @kapilG0

**Comment by kapilG0** [comment]
Hello @omrajsharma I have raised pr of same https://github.com/omrajsharma/bigohhh.com/pull/150. Please check

**Comment by kapilG0** [comment]
Hello @omrajsharma can you please closed this issue

**Comment by kapilG0** [comment]
Hello @omrajsharma . i am closing this issue as pr is already merged for that.
Thanks
