### ISSUE TITLE
Add a new Scroll Bar and fix some issues in Footer Bar

### ISSUE THREAD

**Issue by Abhay182005dat** [omrajsharma/bigohhh.com#108]
Hello Sir,

I would like to customize the scroll bar of the website which will make the website look even more nice and aslo i would like to some allignment issues in Footer of the website .

I request you to please assign this task to me,

Looking forward :)

Thank you.

**Comment by omrajsharma** [comment]
Hi @Abhay182005dat 
#12 is already present so you can work on custom scroll bar.

**Comment by omrajsharma** [comment]
@Abhay182005dat I'm assigning this issue to you. do let me know if you need any help.
