### ISSUE TITLE
Fixing typos error

### ISSUE THREAD

**Issue by NIKHIL0VERMA** [omrajsharma/bigohhh.com#114]
Hey @omrajsharma,
I found some typos. ex:- client/src/components/home/feature.data.tsx line 15 `title: 'Easy Accessable'` should be `title: 'Easy Accessible',`
I would like to fix this. Please add level and tag under GSSOC'24.
Best Regards,
Nikhil Verma

**Comment by omrajsharma** [comment]
Hi @NIKHIL0VERMA 
I'm assigning this issue to you. Do let me know if you need any help.
