### ISSUE TITLE
Want to add an AI chatbot that will handle site specific queries

### ISSUE THREAD

**Issue by aditi9402** [omrajsharma/bigohhh.com#128]
Please assign me this under gssoc.

**Comment by omrajsharma** [comment]
Great idea 💡💯
Can you please share that plan for the feature?

**Comment by aditi9402** [comment]
Sure! The chatbot will look something like this(colours can be changed according to site's color palette):
![Screenshot (562)](https://github.com/omrajsharma/bigohhh.com/assets/114405540/93ede02a-ebe0-4e46-8ea6-0259993a4d50)
![Screenshot (561)](https://github.com/omrajsharma/bigohhh.com/assets/114405540/c788a488-1642-40a0-8277-a93a7ec487d6)
Basically I will train the chatbot on the site's database, and it will then be able to answer any queries.
For example, do you offer any course on web development?
The chatbot will reply Yes along with the courses' features.
