### ISSUE TITLE
Backend Setup for the Project

### ISSUE THREAD

**Issue by soham0005** [omrajsharma/bigohhh.com#131]
Backend Setup with good architecture

1) Authentication and Authorization using JWT
2) User Related Information Storage
3) Firm Backend

**Comment by soham0005** [comment]
@omrajsharma let me work on this issue under gssoc label

**Comment by abhiperfect** [comment]
> @omrajsharma let me work on this issue under gssoc label
Hello @soham0005 , 
This issue is already covered under #51, so i am closing this issue.
