### ISSUE TITLE
[BUG]:Mobile Navigation Box Does Not Automatically Close When Navigating

### ISSUE THREAD

**Issue by Sujal7ss** [omrajsharma/bigohhh.com#133]
I encountered an issue where the navigation box in the mobile view did not automatically close when navigating through any navigation items. This behavior is undesirable as it obstructs the user's view of the content after selecting a navigation option.

**Steps to Reproduce**:

1. Open the application in a mobile viewport.
2. Click on a navigation item to navigate to a different section/page.
3. Observe that the navigation box remains open, obscuring the content of the page.
4. Expected Behavior:
5. When a navigation item is clicked in the mobile view, the navigation box should automatically close to provide an unobstructed view of the content.

**Actual Behavior**:
The navigation box does not close automatically after navigating to a different section/page in the mobile view.

**Solution**:
To address this issue, we need to add functionality to the Navigation component to automatically close the navigation box when a navigation item is clicked in the mobile view. This can be achieved by utilizing a function to toggle the visibility of the navigation box and calling this function when a navigation item is clicked.

@omrajsharma  please add GSSOC label and level to it.
I am a GSSOC contributor and i have already solved this issue. Please assign it to me and i will make a PR.
<img width="245" alt="a" src="https://github.com/omrajsharma/bigohhh.com/assets/104003078/42610416-1449-4a01-8588-6018fe253e01">

<img width="245" alt="v" src="https://github.com/omrajsharma/bigohhh.com/assets/104003078/6e77ce6e-d741-4e2c-91b9-71566b1981b3">

**Comment by abhiperfect** [comment]
Hi @Sujal7ss , Good to know you find a bug, i am assigning this issue to you.

**Comment by Sujal7ss** [comment]
Facing some issues @abhiperfect 
Every changes i have made are wroking fine on my end. 
Please review my commits

**Comment by Sujal7ss** [comment]
@abhiperfect All the errors are resolved. Please check the PR
