### ISSUE TITLE
Adding a link to GitHub icon in the footer Section

### ISSUE THREAD

**Issue by Abh-I-seK** [omrajsharma/bigohhh.com#156]
There is no link for this repo in the website footer, when clicked on the github icon.

Following screenshot is from the footer-social-links.tsx
![Screenshot 2024-05-21 230844](https://github.com/omrajsharma/bigohhh.com/assets/134422863/bf3e92e7-c62e-46c2-8214-c5bc4a9ceda6)

Could you please assign this issue to me under GSSOC 24.

**Comment by aasthabagrawal** [comment]
Plz assign this task to me.
