### ISSUE TITLE
Missing learn.md file

### ISSUE THREAD

**Issue by Meetjain1** [omrajsharma/bigohhh.com#168]
Learn.md file is missing in our current repository 
The learn.md file in GitHub is typically used as a resource to provide guidance, tutorials, or educational content related to a specific repository. This file can serve various purposes, such as introducing new users to the project, providing detailed instructions for using the codebase, or offering learning pathways for different topics covered by the repository.

@omrajsharma assign this issue to me I will add it,

**Comment by harshitayadavv** [comment]
Hey @omrajsharma !!
The learn.md file is really important because it serves as a central place for newcomers to learn about the project. It can include things like project details, setup instructions, tutorials and explanations of project. Please assign this task to me under GSSoC'24.
