### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by sanjay-kv** [omrajsharma/bigohhh.com#2]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow [these](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project#adding-a-code-of-conduct-using-a-template) instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by omrajsharma** [comment]
sure @suhanipaliwal , I'm assigning this to you

**Comment by omrajsharma** [comment]
do let me know if you need any help

**Comment by Vdcds** [comment]
hey @omrajsharma  this project is using nextjs 12 while the latest version of next is 14 may I ask why is that?

**Comment by suhanipaliwal** [comment]
Please add a label of appropriate level like level 1, 2 or 3 for GSSOC'24 on this issue.

**Comment by omrajsharma** [comment]
@suhanipaliwal I've updated the tags
