### ISSUE TITLE
[Enhancement]: Improve Expert Mentor Section

### ISSUE THREAD

**Issue by 0xJaskeerat** [omrajsharma/bigohhh.com#29]
The mentor section has a very bad design 

<img width="1440" alt="Screenshot 2024-05-11 at 2 43 46 PM" src="https://github.com/omrajsharma/bigohhh.com/assets/124770018/956e6c93-0c92-4aed-a8a8-0cfe0b19fa1d">

**Comment by omrajsharma** [comment]
I wish you can bring some amazing design on this. I'm assigning this issue to you.
