### ISSUE TITLE
about feature

### ISSUE THREAD

**Issue by nagamukesh** [omrajsharma/bigohhh.com#30]
About feature in the feature is not working 
once assigned, I can fix this issue
please assign this issue to me under gssoc 2024

**Comment by omrajsharma** [comment]
can you please share what is about feature ???

**Comment by nagamukesh** [comment]
the features below "about section" in the "footer" are not working
they are just redirecting to they home page

**Comment by omrajsharma** [comment]
We're developing a new page for about company. #31

**Comment by omrajsharma** [comment]
Closing this issue due to duplication in issue
