### ISSUE TITLE
[Enhancement] : Add README file

### ISSUE THREAD

**Issue by mahekkg** [omrajsharma/bigohhh.com#33]
Hi team
I've been exploring the project's README file and believe there's room for improvement to enhance its clarity and usefulness for both new users and contributors. Improving the README in multiple aspects will not only make it easier for users to understand and utilize the project but also encourage more contributions and engagement from the community. I have already contributed in open source making it easier to contribute.

Looking forward to collaborating on this enhancement!
Please assign this under GSSOC'24.

**Comment by omrajsharma** [comment]
#8 is already exisitng
