### ISSUE TITLE
PR template for contributors

### ISSUE THREAD

**Issue by omrajsharma** [omrajsharma/bigohhh.com#50]

**Comment by DhruvChadha22** [comment]
Hi, I would like to work on this under GSSOC'24.

**Comment by omrajsharma** [comment]
Hi Dhruv, I'm assigning this issue to you

**Comment by DhruvChadha22** [comment]
Please check the linked PR. Also could you please add the level label to this issue since it is required to be counted in the gssoc leaderboards for me. Thanks!
