### ISSUE TITLE
Add Readme.md and learn.md documentation

### ISSUE THREAD

**Issue by SuhainaFathimaM** [omrajsharma/bigohhh.com#58]
No Readme.md and learn.md documentation.. I will work on it

**Comment by SuhainaFathimaM** [comment]
Assign this issue as GSSoC'24 .. 
I would like to work on this issue..
@omrajsharma   Please assign me this issue

**Comment by PrathicaShettyM** [comment]
@omrajsharma Please assign me this issue under GSSoC'24. Please give me 1 chance.

**Comment by omrajsharma** [comment]
this issue is already resolved #8 #48 
If you have any specific enhancement then you can raise it.
