### ISSUE TITLE
Enhancement : Issue with Footer Navigation Links and Missing Contact Page

### ISSUE THREAD

**Issue by Aniket-2504** [omrajsharma/bigohhh.com#65]
Dear @omrajsharma ,

I observed that the navigation links in the footer of your website are not functioning properly. Specifically, these links only navigate to the home section instead of their designated destinations.

Additionally, I noticed that there is a link to a contact page in the footer, but the contact page itself appears to be missing or inaccessible.

I have recorded a video demonstration of the issues to provide a clear understanding. You can view the video here:( Sorry for the video Quality )

https://github.com/omrajsharma/bigohhh.com/assets/145179532/f7fd49c5-abd0-4c87-8064-d36b84414d18

I'm interested in addressing these issues and enhancing the functionality of your website. Please consider assigning me this task, and I will provide my best effort to resolve these navigation and contact page issues.

Thank you for your attention to this matter.

**Comment by omrajsharma** [comment]
Hi @Aniket-2504 
I'm assigning this issue to you. Please fix this issue of navigation. We're going to build other pages as well

**Comment by Aniket-2504** [comment]
Thank you so much @omrajsharma , i will give my best
