### ISSUE TITLE
Broken liveUrl link

### ISSUE THREAD

**Issue by Mr-mahato** [omrajsharma/bigohhh.com#7]
I was trying to view the bigohh.com and i found that the url present here in the github repo has been broken.

**Comment by rajvinder-kaur** [comment]
maybe u should visit vercel and it will show u the problems related to it

**Comment by Mr-mahato** [comment]
@rajvinder-kaur i did tried of opening the project , through the vercel it was 404 , telling that the deployment not found.

**Comment by rajvinder-kaur** [comment]
u tried this 
1) 
![image](https://github.com/omrajsharma/bigohhh.com/assets/93728836/82c65914-9362-4559-aca6-7102b1cfb1f8)
or this one 
2) 
![image](https://github.com/omrajsharma/bigohhh.com/assets/93728836/44d32e50-2011-40ae-a5b4-503cf2d543d4)

**Comment by rajvinder-kaur** [comment]
u can try redeploying it

**Comment by Mr-mahato** [comment]
I tried above one 1)

**Comment by rajvinder-kaur** [comment]
oaky then go to vercel.com and login with your github, and then choose the project from there. it will show u why the link is broken. if it doesnt solve the issue then try deleting the deployment from vercel and redeploy the repository on vercel.
i hope this helps and if dont tell me

**Comment by m-tabish** [comment]
Kindly assign this to me

**Comment by omrajsharma** [comment]
Hey folks,
You can refer to this https://stackoverflow.com/questions/65475998/how-to-fix-an-error-code-not-found-in-vercel

**Comment by omrajsharma** [comment]
I'm assigning this issue to @m-tabish , please look into it. let me know if you need any help.

**Comment by m-tabish** [comment]
ya so i forked and cloned the repo and it is deployed on vercel, here's the link

https://bigohhh-com.vercel.app/

**Comment by m-tabish** [comment]
the link in this repo is working fine.

**Comment by omrajsharma** [comment]
@m-tabish you can checkout this link https://www.bigohhh.com/omrajsharma

**Comment by m-tabish** [comment]
where is this end point 'omrajsharma' supposed to  take you is there any mentor profile page? cause i see many destination in the code but there aren't any pages for them to redirect you, do i have to make that component with name [mentor.js] so that dynamic links work?

**Comment by omrajsharma** [comment]
@m-tabish I can't see any issue on prod url. seems fine to me.

**Comment by m-tabish** [comment]
yes the url is working fine thats what i mentioned in before, but this endpoint is creating the issue cause there is not page dedicated for it, i feel there is no work to be done, but i'll request you to label this issue as gssoc 24 and close this with counting my contribution, I can then move on with making the readme

**Comment by omrajsharma** [comment]
Sure @m-tabish 
thanks for support
