### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by omrajsharma** [omrajsharma/bigohhh.com#8]
Following are the repos for reference of good README.md
- https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects
- https://github.com/abhisheks008/DL-Simplified
- https://github.com/ridsuteri/Awesome-Chrome-Extensions

**Comment by m-tabish** [comment]
I can do it

**Comment by omrajsharma** [comment]
Hey @m-tabish 
Thanks for showing interest. I'm assigning this issue to you. if you need any help, do let me know.

**Comment by m-tabish** [comment]
I am currently working on this.

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by omrajsharma** [comment]
This issue is already assigned to @m-tabish

**Comment by Suruchibharti** [comment]
hii ,
I'm GSSoC'24 contributor , I have experienced on HTML, CSS, JS, and react.js , so I want to work on this issue,
so, kindly requested to you to assign me the task.

**Comment by omrajsharma** [comment]
@m-tabish any update on this issue ??

**Comment by m-tabish** [comment]
Yep doing a PR in some time, sry for the long wait

**Comment by m-tabish** [comment]
Kindly add level label also

**Comment by omrajsharma** [comment]
@

**Comment by m-tabish** [comment]
@omrajsharma kindly add labels in this PR cause without them the points wont be counted
