### ISSUE TITLE
Automatic Greeting Github Bot

### ISSUE THREAD

**Issue by Hemu21** [omrajsharma/bigohhh.com#84]
Currently This repo does not have greeting bot. As it is a open source so many people create the issues. There is No one to greet the issue creator. GitHub greeting Bot will automatically greet them when they create a issue. I can create the github greeting bot.

**Comment by Hemu21** [comment]
@omrajsharma can you please assign this to me.

**Comment by omrajsharma** [comment]
#61 this issue is already defined.

**Comment by Hemu21** [comment]
@omrajsharma  ok
