### ISSUE TITLE
Implement sticky navbar throughout the pages

### ISSUE THREAD

**Issue by chhavx1618** [omrajsharma/bigohhh.com#85]
Allow the navbar to be visible on the top of the screen over every page making it easier for users to navigate to different sections and pages. 

Under GSSOC'24 I would like to work on this issue and improve the UI and usability of this project.

![image](https://github.com/omrajsharma/bigohhh.com/assets/152146397/40f34b06-a77c-41de-b0cd-2003d1289a5f)

**Comment by Kalyan9064** [comment]
issue is already discuss in issue number #76

**Comment by omrajsharma** [comment]
@chhavx1618 
This issue is already resolved #70 . Effort is appreciated. You can look for some other issue in the issues section of this repo.

**Comment by omrajsharma** [comment]
I'm closing this issue
